#! /usr/bin/env python
# encoding: utf-8

def build(ctx):

    if ctx.options.all:

        ctx.program(
            target = 'clas12-geometry-request',
            source = ['clas12-geometry-request.cpp'],
            use = '''\
                C++11
                BOOST
                    boost_program_options
                PUGIXML
                    pugixml
                CLARA
                CTOOLBOX
                CMSG
                EVIO
                EXPAT
            '''.split())

        '''
        ctx.program(
            target = 'clas12geom-request',
            source = ['clas12geom-request.cpp'],
            use = ''  '\
                C++11
                BOOST
                    boost_program_options
                PUGIXML
                    pugixml
                CLARA
                CMSG
            '' '.split())
        '''
