#! /usr/bin/env python
# encoding: utf-8

def build(ctx):

    ctx.program(
        target = 'clas12geom',
        source = ['clas12geom.cpp'],
        includes = ['#src'],

        use = '''
            C++11
            BOOST
                boost_program_options
            CCDB
                MYSQL
            GEOMETRY
            PUGIXML
                pugixml
            clas12_geometry
        '''.split())

    if ctx.env.HAVE_EVIO:
        ctx.program(
            target = 'clas12magfield',
            source = ['clas12magfield.cpp'],
            includes = ['#src'],

            use = '''
                C++11
                BOOST
                    boost_program_options
                EVIO
                    EXPAT
                clas12_magfield
            '''.split())

    if ctx.options.gemc or ctx.options.all:
        ctx.shlib(
            target = 'clas12_geometry_gemc',
            source = ['gemc/clas12_geometry_gemc.cpp'],
            includes = ['#src'],

            use = '''
                C++11
                BOOST
                CCDB
                    MYSQL
                GEOMETRY
                PUGIXML
                    pugixml
                clas12_geometry
            '''.split())

